[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:vncserver]
command=/bin/bash -c "rm -rf /tmp/.X1-lock /tmp/.X11-unix/X1; /usr/bin/vncserver :1 -geometry 1280x800 -depth 24 -localhost yes -SecurityTypes None -fg"
autorestart=true
stdout_logfile=/tmp/vncserver.log
stderr_logfile=/tmp/vncserver.err.log

[program:websockify]
command=/usr/bin/websockify --web=/usr/share/novnc 8080 localhost:5901
autorestart=true
stdout_logfile=/tmp/websockify.log
stderr_logfile=/tmp/websockify.err.log